# cloudbuild.yaml

steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - "us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/order-app:${COMMIT_SHA:-latest}"
      - '.'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - "us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/order-app:${COMMIT_SHA:-latest}"

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud run deploy order-app \
          --image=us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/order-app:${COMMIT_SHA:-latest} \
          --region=us-central1 \
          --platform=managed \
          --allow-unauthenticated \
          --port=80 \
          --quiet

options:
  logging: CLOUD_LOGGING_ONLY
